### ISSUE TITLE
Does not work for iOS7

### ISSUE THREAD

**Issue by LightMan** [ziryanov/CCGrowingTextView#1]
I think the problem with contextSize in iOS7 is not treated

**Comment by ziryanov** [comment]
Please look at example project. Does it work properly for you? If not, please provide more information

**Comment by LightMan** [comment]
Hi,

I executed the example project, when the caret reaches the last line, then
if you want to go to the next line (pressing return) the textview will not
scroll up. This is a common problem in iOS7 since uitextview's contentSize
is not updated when there is a newline. Just execute your example project
in a iOS7 simulator, press return several times and you will see the
problem.

**Comment by ziryanov** [comment]
This is default behaviour of UITextView. If Apple fix that then this bug will automatically disappear in my control.
