### ISSUE TITLE
Not working when create in Interface Builder with Xcode 6.2

### ISSUE THREAD

**Issue by thehellsoul** [ziryanov/CCGrowingTextView#5]
1/ I create a **UITextView** then change its class to **CCGrowingTextView** but it doesn't work at all.
2/ I copy **CCGrowingTextView** from your example and paste it to my test storyboard Interface Builder and it work.

**Comment by Woildan** [comment]
If you are using AutoLayout, make sure to give a lower priority to the height constraint of your text view than to the "Content Compression Resistance" priority (CCGrowingTextView uses intrinsicContentSize to inform AutoLayout about the desired height).
